version: '3.8'
services:
#backend part

  #backend:
  #  build: .
  #  ports:
  #    - "8080:8080"
  #  depends_on:
  #    - postgres

#DB part
  postgres:
    image: postgis/postgis:15-3.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: EcoMentorDB
      POSTGRES_USER: EcoMentor
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
 postgres-data:
