package com.EcoMentor_backend.EcoMentor.User.useCases.mapper;

import com.EcoMentor_backend.EcoMentor.User.entity.User;
import com.EcoMentor_backend.EcoMentor.User.useCases.dto.CreateUserDTO;
import com.EcoMentor_backend.EcoMentor.User.useCases.dto.UserDTO;
import org.springframework.stereotype.Component;

@Component
public class UserMapper {

    // Entity to DTO conversion. The id field is included in the DTO.
    public UserDTO toDTO(User user) {
        if (user == null) {
            return null;
        }
        return UserDTO.builder()
                .name(user.getName())
                .email(user.getEmail())
                .password(user.getPassword())
                .id(user.getId())
                .build();
    }

    // CreateDTO to Entity. CreateDTO does not have an id field because it is generated by the database.
    public User toEntity(CreateUserDTO dto) {
        if (dto == null) {
            return null;
        }
        return User.builder()
                .name(dto.getName())
                .email(dto.getEmail())
                .password(dto.getPassword())
                .build();
    }

}
