package com.EcoMentor_backend.EcoMentor.User.useCases.mapper;

import com.EcoMentor_backend.EcoMentor.Certificate.useCases.mapper.CertificateMapper;
import com.EcoMentor_backend.EcoMentor.User.entity.User;
import com.EcoMentor_backend.EcoMentor.User.useCases.dto.CreateUserDTO;
import com.EcoMentor_backend.EcoMentor.User.useCases.dto.UserDTO;
import java.util.stream.Collectors;
import org.springframework.stereotype.Component;


@Component
public class UserMapper {

    private final CertificateMapper certificateMapper;


    public UserMapper(CertificateMapper certificateMapper) {
        this.certificateMapper = certificateMapper;
    }

    public UserDTO toDTO(User user) {
        if (user == null) {
            return null;
        }
        return UserDTO.builder()
                .name(user.getName())
                .email(user.getEmail())
                .password(user.getPassword())
                .id(user.getId())
                .certificateDTOList(user.getCertificates().stream().map(certificateMapper::toDTO)
                        .collect(Collectors.toList()))
                .build();
    }

    // CreateDTO to Entity. CreateDTO does not have an id field because it is generated by the database.
    public User toEntity(CreateUserDTO dto) {
        if (dto == null) {
            return null;
        }
        return User.builder()
                .name(dto.getName())
                .email(dto.getEmail())
                .password(dto.getPassword())
                .build();
    }

}