package com.EcoMentor_backend.EcoMentor.Address.useCases.mapper;

import com.EcoMentor_backend.EcoMentor.Address.entity.Address;
import com.EcoMentor_backend.EcoMentor.Address.useCases.dto.CreateAddressDTO;
import com.EcoMentor_backend.EcoMentor.Address.useCases.dto.AddressDTO;
import org.springframework.stereotype.Component;

@Component
public class AddressMapper {

    // Entity to DTO conversion. The id field is included in the DTO.
    public AddressDTO toDTO(Address address) {
        if (address == null) {
            return null;
        }
        return AddressDTO.builder()
                .addressId(address.getAddressId())
                .addressName(address.getAddressName())
                .addressNumber(address.getAddressNumber())
                .zipcode(address.getZipcode())
                .town(address.getTown())
                .region(address.getRegion())
                .province(address.getProvince())
                .longitude(address.getLongitude())
                .latitude(address.getLatitude())
                .build();
    }

    // CreateDTO to Entity. CreateDTO does not have an id field because it is generated by the database.
    public Address toEntity(CreateAddressDTO dto) {
        if (dto == null) {
            return null;
        }
        return Address.builder()
                .addressName(dto.getAddressName())
                .addressNumber(dto.getAddressNumber())
                .zipcode(dto.getZipcode())
                .town(dto.getTown())
                .region(dto.getRegion())
                .province(dto.getProvince())
                .longitude(dto.getLongitude())
                .latitude(dto.getLatitude())
                .build();
    }
}