name: CI

on:
  push:
    branches: [ "main", "dev", "ci_pipeline" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up OpenJDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          architecture: 'x64'
          distribution: 'temurin'
          cache: 'maven'

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Run Docker Container
        run: docker compose up -d

      - name: Clean Project
        run: mvn clean

      - name: Compile Project
        run: mvn compile

      - name: Run Tests
        run: mvn test

      - name: Stop Docker Container
        if: always()
        run: docker compose down -v

  checkstyle:
    name: Checkstyle Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up OpenJDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          architecture: 'x64'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Checkstyle
        run: mvn checkstyle:check -Pcheckstyle-only -Dorg.checkstyle.google.severity=error
